<?php
$CONFIG = array (
  'passwordsalt' => 'IDQZrHKr+kvU7TV+ODAYzEuwIXWeQM',
  'secret' => 'gEKbuvtRqvWk5sNkuhazD8KnwM1ywRTgdjmTRjliPO9mt/yG',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.udobnidom.ru',
    1 => '192.168.2.145',
    2 => 'localhost',
  ),
  'datadirectory' => '/nc_data',
  'dbtype' => 'mysql',
  'version' => '33.0.2.2',
  'overwrite.cli.url' => 'https://nextcloud.udobnidom.ru',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ncp',
  'dbpassword' => 'hao12wanr#',
  'instanceid' => 'oc0jw0dierom',
  'installed' => true,
  'overwritehost' => 'nextcloud.udobnidom.ru',
  'activity_expire_days' => 14,
  'allow_local_remote_servers' => true,
  'auth.bruteforce.protection.enabled' => true,
  'forbidden_filenames' => 
  array (
    0 => '.htaccess',
    1 => 'Thumbs.db',
    2 => 'thumbs.db',
  ),
  'cron_log' => true,
  'default_phone_region' => 'DE',
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\HEIC',
    11 => 'OC\\Preview\\Movie',
    12 => 'OC\\Preview\\MKV',
    13 => 'OC\\Preview\\MP4',
    14 => 'OC\\Preview\\AVI',
  ),
  'filesystem_check_changes' => 0,
  'filelocking.enabled' => 'true',
  'htaccess.RewriteBase' => '/',
  'integrity.check.disabled' => false,
  'knowledgebaseenabled' => false,
  'log_rotate_size' => '104857600',
  'logfile' => '/var/log/nextcloud/nextcloud.udobnidom.ru.log',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Berlin',
  'remember_login_cookie_lifetime' => 36000,
  'session_lifetime' => 36000,
  'session_keepalive' => true,
  'auto_logout' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'minimum.supported.desktop.version' => '4.0.1',
  'overwriteprotocol' => 'https',
  'preview_max_x' => 1024,
  'preview_max_y' => 768,
  'preview_max_scale_factor' => 1,
  'profile.enabled' => false,
  'redis' => 
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'password' => '1773ae5421ae053820f91752acf5c56e',
    'timeout' => 0.5,
    'dbindex' => 1,
  ),
  'quota_include_external_storage' => false,
  'share_folder' => '/Freigaben',
  'skeletondirectory' => '',
  'trashbin_retention_obligation' => 'auto, 7',
  'maintenance_window_start' => 1,
  'maintenance' => false,
  'trusted_proxies' => 
  array (
    0 => '192.168.2.206',
    1 => '192.168.2.145',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
  'app_install_overwrite' => 
  array (
    0 => 'caniupdate',
  ),
);
