[http]
listen = 0.0.0.0:8080

[app]
debug = false

[sessions]
hashkey = rDR4ySPAXhsBjlvEOnYL3fMeH1koq5pG8JutU9xwdaK2cTCZ
blockkey = rDR4ySPAXhsBjlvEOnYL3fMeH1koq5pG

[clients]
internalsecret = rDR4ySPAXhsBjlvEOnYL3fMeH1koq5pG8JutU9xwdaK2cTCZ

[backend]
allowall = true
secret = rDR4ySPAXhsBjlvEOnYL3fMeH1koq5pG8JutU9xwdaK2cTCZ
timeout = 10
connectionsperhost = 8
skipverify = true

[nats]
url = nats://loopback

[turn]
apikey = hpbApiKeytwoRHTqEP6lcMQv41Xxag9jm
secret = 9jzi4KplMd1qmSsXFch3AIeN0Y6rnBOWTQbyuaoZEUv5kt2w
servers = turn:nextcloud.udobnidom.ru:3478?transport=udp,turn:nextcloud.udobnidom.ru:3478?transport=tcp
